name: take_eat
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.3
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_storage: ^13.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  google_sign_in: ^7.2.0
  hexcolor: ^3.0.1
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.16.0
  responsive_framework: ^1.5.1
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.2.1
  freezed_annotation: ^3.1.0
  injectable: ^2.5.1
  freezed: ^3.2.3
  crypto: ^3.0.6

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  freezed: ^3.1.1
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/svgs/
    - assets/images/icons/

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Thin.ttf
          weight: 100
        - asset: assets/fonts/LeagueSpartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/LeagueSpartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LeagueSpartan-Black.ttf
          weight: 900
