// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmm44dY2YCmdIuuUXZ0AvhTVQ9UVKyVGQ',
    appId: '1:375336328915:android:ccb3d76ad4f3ad8b9d7e26',
    messagingSenderId: '375336328915',
    projectId: 'foodapp-9562c',
    databaseURL: 'https://foodapp-9562c-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-9562c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx7t9Ynwn37CWy1Igz0RvUK8vg07JFXr4',
    appId: '1:375336328915:ios:6e31a2c55bb5a8eb9d7e26',
    messagingSenderId: '375336328915',
    projectId: 'foodapp-9562c',
    databaseURL: 'https://foodapp-9562c-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-9562c.firebasestorage.app',
    iosClientId: '375336328915-r3hmg1ruas0i8puu9fq7jbd2sq75u9mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.take-eat',
  );

}